### ISSUE TITLE
changelog and readme files

### ISSUE THREAD

**Issue by rs028** [MistraModel/KPP-Mistra#10]
- [x] update `CHANGELOG` file (change to markdown)
- [ ] ~add info in `diff_version_rolf_sander.txt` to `changelog`~
- [x] tidy up `readme` file (change to markdown)
- [x] update `KPP_VERSION`

After this is done and PR#7 is merged -> **New Release**

**Comment by pb866** [comment]
PR #7 already includes a transformation of the README to markdown. So probably, merge it first and add changes afterwards.

**Comment by rs028** [comment]
Resolved by #12.
